EMAIL_SUBJECT = "StudentDetails | {}"
EMAIL_FROM = 'no.reply.tnpproject@gmail.com'
EMAIL_TO = ['utkarshmkhursale@gmail.com']
MESSAGE_BODY = "Please find attached File with the requested Details."
PATH_TO_CSV_FILE = "C:\\Users\\Utkarsh Khursale\\relationalDBManagementSystem\\backEnd\\outputs\\StudentDetails.csv"
FILE_NAME = "studentDetails_{}.csv"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "no.reply.tnpproject@gmail.com"
SMTP_PASSWORD = "aykewuftgquwrshm"
