# Generated by Django 4.0.1 on 2022-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.PositiveIntegerField(),
        ),
    ]
