# Generated by Django 4.0.1 on 2022-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
