# Generated by Django 4.0.1 on 2022-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
